**Primos de Mersenne y números perfectos.**

**a)**  Determina para qué valores de $n$ entre 1 y 10 son primos los números $M_n=2^n-1$. A la vista de los resultados, ¿te atreves a conjeturar cuándo lo serán para otros valores de $n$?  Los primos de la forma $M_n$ se denominan primos de Mersenne en memoria del filósofo del siglo XVII Marin Mersenne, quien los estudió en su obra *Cognitata Physico-Mathematica*.

In [1]:
for j in [1..10]:
    print(j,(2^j-1).is_prime())

1 False
2 True
3 True
4 False
5 True
6 False
7 True
8 False
9 False
10 False


> **Conjetura** (sobre los primos de Mersenne) El número de la forma $2^n-1$ es primo si $n$ es primo.

>> **Ojo**: solo lo hemos comprobado para los $n$ entre $1$ y $10$.

______________
**b)** Repite el apartado a) para $n$ entre 11 y 20. ¿Cambia tu conjetura?

In [2]:
for j in [11..20]:
    print(j,(2^j-1).is_prime())

11 False
12 False
13 True
14 False
15 False
16 False
17 True
18 False
19 True
20 False


>> La conjetura anterior ha sido rebatida por $n=11$ (¡poco ha durado!). Podría tratarse de una excepción, habría que mirar algunos más, pero leyendo el siguiente apartado desistimos. Lo que sí parece mantenerse es esta nueva conjetura.

> **Conjetura** (sobre los primos de Mersenne) Si $2^n-1$ es primo, a la fuerza $n$ es primo.


_______________
**c)** Mersenne conjeturó que había una cantidad finita de primos de la forma $M_n$, concretamente los correspondientes a
$$
n=2,3,5,7,13,17,19,31,67,127,257.
$$
Mersenne se equivocó doblemente. Por una parte, no todos los $n$ de esta lista producen un primo. Detecta, con la ayuda de Sage, cuáles son los que no lo hacen. Por otra, hay primos de Mersenne correspondientes a valores de $n$ que no están en esta lista. Comprueba que ese es el caso si
$$
n=61, 89, 107, 521,607,1279.
$$

En agosto de 2020 se conocían 51 primos de Mersenne. El mayor, $M_{82 589 933}$, era el mayor primo conocido hasta ese momento. No se sabe si hay más.

In [3]:
candidatos=[2,3,5,7,13,17,19,31,67,127,257]
Fallos=[]
for j in candidatos:
    if not((2^j-1).is_prime()):
        Fallos.append(j)
print('Mersenne se equivocó para los valores: %s'%Fallos)

Mersenne se equivocó para los valores: [67, 257]


In [4]:
for j in Fallos:
    candidatos.remove(j)
candidatos.extend([61,89,107,521,607,1279])   
candidatos.sort()
print(candidatos)

[2, 3, 5, 7, 13, 17, 19, 31, 61, 89, 107, 127, 521, 607, 1279]


In [5]:
all([(2^j-1).is_prime() for j in candidatos])

True

__________________
**d)**  Un número perfecto es un entero positivo que es igual a la suma de sus divisores propios positivos.
Así, 6 es un número perfecto porque sus divisores propios son 1, 2 y 3, y 6 = 1 + 2 + 3. Definir una función $\verb=perfecto(k)=$ que dado un entero positivo $\texttt{k}$ devuelva $\texttt{True}$ si $\texttt{k}$ es perfecto y $\texttt{False}$ en caso contrario.

*Sugerencia.* Puede ser útil usar el método $\texttt{divisors()}$.

In [6]:
def perfecto(k):
    suma=0
    for j in k.divisors():
        suma=suma+j
    return suma==2*k

In [7]:
perfecto(6)

True

In [8]:
Perfectos=[j for j in xsrange(1,10^4) if perfecto(j)]
Perfectos

[6, 28, 496, 8128]

> Una versión muy corta, tan corta que no justifica el que se defina una función para tal fin.

In [9]:
def perfecto(k):
    return sum(k.divisors())==2*k

In [10]:
Perfectos=[j for j in xsrange(1,10^4) if perfecto(j)]
Perfectos

[6, 28, 496, 8128]

__________________
**e)** Euclides ya sabía de la existencia de primos de Mersenne muchos siglos antes que este, y encontró una fuerte relación entre ellos y los números perfectos.  Concretamente,  el último resultado de la parte de teoría de números de sus *Elementos* establece que si $M$ es un  primo de Mersenne, entonces $M(M+1)/2$ es un número perfecto par. Comprueba esta afirmación para los diez primeros primos de Mersenne. 

*Observación previa:* por los apartados anteriores sé que $M_n$ es primo para 2, 3, 5, 7, 13, 17, 19, 31, 127 (conocido por Mersenne, apartado c)), y en el apartado d) lo hemos visto para 61, 89, 107, 521, 607, 1279. Es decir, los diez valores más pequeños de $n$ para los que sabemos que $M_n$ es primo son 2, 3, 5, 7, 13, 17, 19, 31, 61, 89. Realmente no sé seguro si estos son los diez primeros primos de Mersenne: voy a comprobarlo:



In [11]:
## Basta mirar si antes del exponente 89 hay alguno más.
Faltan=[]
for j in [1..89]:
    Mj=2^j-1
    if (2^j-1).is_prime() and j not in candidatos:
        Faltan.append(j)
if Faltan:
    print('Faltaban: %s'%Faltan)
else:
    print('Están localizados los 10 primeros')

Están localizados los 10 primeros


In [12]:
##La afirmación a verificar:
Respuestas=[]
for j in candidatos[:10]:
    Mj=2^j-1
    Respuestas.append(perfecto((Mj*(Mj+1))//2))
all(Respuestas)    

True

__________
**f)** Muchos siglos después, Euler demostró el recíproco: si un número $n$ es perfecto y par, entonces es de la forma $M(M+1)/2$ para algún primo de Mersenne. Obtén la lista de todos los números perfectos pares menores o iguales que $M_{13}(M_{13}+1)/2$ y comprueba que todos ellos son de la forma $M(M+1)/2$ para algún primo de Mersenne $M$.

In [13]:
%time
M13=2^(13)-1
tope=M13*(M13+1)//2+1
Parfectos=[j for j in xsrange(2,tope,2) if perfecto(j)]

CPU times: user 0 ns, sys: 5 µs, total: 5 µs
Wall time: 21.9 µs


In [14]:
Parfectos

[6, 28, 496, 8128, 33550336]

In [15]:
Emes=[(sqrt(1+8*k)-1)/2 for k in Parfectos]
Emes

[3, 7, 31, 127, 8191]

In [16]:
Emes==[2^j-1 for j in [2, 3, 5, 7, 13]]

True

____________
**g)** A día de hoy no se sabe si hay algún número perfecto impar. Comprueba que no hay ninguno menor que un millón.

In [17]:
any([perfecto(k) for k in xsrange(1,10^6,2)])

False