**Primos de Mersenne y números perfectos.**

**a)**  Determina para qué valores de $n$ entre 1 y 10 son primos los números $M_n=2^n-1$. A la vista de los resultados, ¿te atreves a conjeturar cuándo lo serán para otros valores de $n$?  Los primos de la forma $M_n$ se denominan primos de Mersenne en memoria del filósofo del siglo XVII Marin Mersenne, quien los estudió en su obra *Cognitata Physico-Mathematica*.

In [23]:
var('a')
def mi_funcion(arg1):
    for n in range(arg1):
        a=2^(n+1)-1
        if is_prime(a):
            print(a," es primo ",n+1)
        else:    
            print(a," es NO primo",n+1)
        
print("Mn es primo cuando n vale 2,3,5,7")
print("Por lo que me atrevo a pensar que Mn es primo cuando n es primo")


1  es NO primo 1
3  es primo  2
7  es primo  3
15  es NO primo 4
31  es primo  5
63  es NO primo 6
127  es primo  7
255  es NO primo 8
511  es NO primo 9
1023  es NO primo 10
Mn es primo cuando n vale 2,3,5,7
Por lo que me atrevo a pensar que Mn es primo cuando n es primo


> **Conjetura** (sobre los primos de Mersenne) ....

______________
**b)** Repite el apartado a) para $n$ entre 11 y 20. ¿Cambia tu conjetura?

In [115]:
    for n in range(20):
        a=2^(n+1)-1
        if is_prime(a):
            print(a," es primo ",n+1)
        else:    
            print(a," es NO primo",n+1)
            
print(2^13-1)

1  es NO primo 1
3  es primo  2
7  es primo  3
15  es NO primo 4
31  es primo  5
63  es NO primo 6
127  es primo  7
255  es NO primo 8
511  es NO primo 9
1023  es NO primo 10
2047  es NO primo 11
4095  es NO primo 12
8191  es primo  13
16383  es NO primo 14
32767  es NO primo 15
65535  es NO primo 16
131071  es primo  17
262143  es NO primo 18
524287  es primo  19
1048575  es NO primo 20
8191


> **Conjetura** (sobre los primos de Mersenne) ....

In [28]:
print("Mi conjetura cambia, no todos los primos hacen que 2^n sea primo")

Mi conjetura cambia, no todos los primos hacen que 2^n sea primo


_______________
**c)** Mersenne conjeturó que había una cantidad finita de primos de la forma $M_n$, concretamente los correspondientes a
$$
n=2,3,5,7,13,17,19,31,67,127,257.
$$
Mersenne se equivocó doblemente. Por una parte, no todos los $n$ de esta lista producen un primo. Detecta, con la ayuda de Sage, cuáles son los que no lo hacen. Por otra, hay primos de Mersenne correspondientes a valores de $n$ que no están en esta lista. Comprueba que ese es el caso si
$$
n=61, 89, 107, 521,607,1279.
$$

En agosto de 2020 se conocían 51 primos de Mersenne. El mayor, $M_{82 589 933}$, era el mayor primo conocido hasta ese momento. No se sabe si hay más.

In [35]:
L=[2,3,5,7,13,19,31,127,257]
P=[61,89,107,521,607,1279]
for element in L:
    a=2^(element)-1
    if is_prime(a):
        print(a," es primo ",element)
    else:    
        print(a,"NO es primo",element)
        
for element in P:
    a=2^(element)-1
    if is_prime(a):
        print(a," es primo ",element)
    else:    
        print(a,"NO es primo",element)
        
print("Se confirma todo lo que dice el enunciado, n=257 no prudce un primo y de la segunda lista todos producen primos")

        

3  es primo  2
7  es primo  3
31  es primo  5
127  es primo  7
8191  es primo  13
524287  es primo  19
2147483647  es primo  31
170141183460469231731687303715884105727  es primo  127
231584178474632390847141970017375815706539969331281128078915168015826259279871 NO es primo 257
2305843009213693951  es primo  61
618970019642690137449562111  es primo  89
162259276829213363391578010288127  es primo  107
6864797660130609714981900799081393217269435300143305409394463459185543183397656052122559640661454554977296311391480858037121987999716643812574028291115057151  es primo  521
531137992816767098689588206552468627329593117727031923199444138200403559860852242739162502265229285668889329486246501015346579337652707239409519978766587351943831270835393219031728127  es primo  607
104079321946643990819252403273640855386152622472667048053191123504036080596733602980122394417323241848424216139542810077913835662483234649081399066056773207629241295093892203457731833496615835504729594205476898112116936771475

__________________
**d)**  Un número perfecto es un entero positivo que es igual a la suma de sus divisores propios positivos.
Así, 6 es un número perfecto porque sus divisores propios son 1, 2 y 3, y 6 = 1 + 2 + 3. Definir una función $\verb=perfecto(k)=$ que dado un entero positivo $\texttt{k}$ devuelva $\texttt{True}$ si $\texttt{k}$ es perfecto y $\texttt{False}$ en caso contrario.

*Sugerencia.* Puede ser útil usar el método $\texttt{divisors()}$.

In [95]:

var('a k')
def perfecto(k):
    a=0
    L=divisors(k)
    for i in L:
        a=a+i
    if a==2*k :
        #print(k,"es perfecto")
        return true
    else:
        #print(k,"NO es perfecto")
        return false
perfecto(6)
    

True

__________________
**e)** Euclides ya sabía de la existencia de primos de Mersenne muchos siglos antes que este, y encontró una fuerte relación entre ellos y los números perfectos.  Concretamente,  el último resultado de la parte de teoría de números de sus *Elementos* establece que si $M$ es un  primo de Mersenne, entonces $M(M+1)/2$ es un número perfecto par. Comprueba esta afirmación para los diez primeros primos de Mersenne. 

*Observación previa:* por los apartados anteriores sé que $M_n$ es primo para 2, 3, 5, 7, 13, 17, 19, 31, 127 (conocido por Mersenne, apartado c)), y en el apartado d) lo hemos visto para 61, 89, 107, 521, 607, 1279. Es decir, los diez valores más pequeños de $n$ para los que sabemos que $M_n$ es primo son 2, 3, 5, 7, 13, 17, 19, 31, 61, 89. Realmente no sé seguro si estos son los diez primeros primos de Mersenne: voy a comprobarlo:



In [125]:
def primeros_primos(m):
    flag=0
    i=0
    n=0
    while flag==0:
        a=2^(n+1)-1
        if is_prime(a):
            print(a," es primo ",n+1)
            i=i+1
        #else:    
            #print(a," es NO primo",n+1)
        n+=1
        if m==i:
            flag=1
            
primeros_primos(10)
print("Ya tenemos los primeros 10 primos de Mersenne")
lista=[2,3,5,7,13,17,19,31,61,89]

for element in lista:
    a=2^element-1
    b=(a*(a+1))/2
    if perfecto(b) and b%2==0:
        print("Se cumple para",element)
        
print("Se ve que se cumple")

3  es primo  2
7  es primo  3
31  es primo  5
127  es primo  7
8191  es primo  13
131071  es primo  17
524287  es primo  19
2147483647  es primo  31
2305843009213693951  es primo  61
618970019642690137449562111  es primo  89
Ya tenemos los primeros 10 primos de Mersenne
Se cumple para 2
Se cumple para 3
Se cumple para 5
Se cumple para 7
Se cumple para 13
Se cumple para 17
Se cumple para 19
Se cumple para 31
Se cumple para 61
Se cumple para 89
Se ve que se cumple


__________
**f)** Muchos siglos después, Euler demostró el recíproco: si un número $n$ es perfecto y par, entonces es de la forma $M(M+1)/2$ para algún primo de Mersenne. Obtén la lista de todos los números perfectos pares menores o iguales que $M_{13}(M_{13}+1)/2$ y comprueba que todos ellos son de la forma $M(M+1)/2$ para algún primo de Mersenne $M$.

In [132]:
m=2^13-1
p=m*(m+1)/2
show(p)
for i in range(1,p):

    
    
    if perfecto(i) and i%2==0 :
        print(i," Lo cumple")
        
print("Comprobamos si son de la forma esa para algun primo de Mersenne")


    
        
        
    




33550336

6  Lo cumple
28  Lo cumple
496  Lo cumple
8128  Lo cumple
Comprobamos si son de la forma esa para algun primo de Mersenne


In [144]:
lista=[6,28,496,8128,33550336]




for element in lista:
    show((sqrt(1+8*element)-1)/2)
    
    
lista2=[3,7,31,127,8191]
lista3=[2, 3, 5, 7, 13]

lista2==[2^i-1 for i in lista3]

3

7

31

127

8191

True

____________
**g)** A día de hoy no se sabe si hay algún número perfecto impar. Comprueba que no hay ninguno menor que un millón.

In [149]:
for i in range(1,10^6):
    if i%2==1 and perfecto(i):
        print("true")
